"""
seed_data.py
Comprehensive authentic healthcare network dataset for India's National Health Supply Chain.
Includes ALL 36 States & Union Territories of India (28 States, 8 UTs), 114+ Health Facilities
(PHCs, CHCs, DHs) with authentic geo-coordinates, NLEM Essential Medicines, Bed Capacities,
Healthcare Staff Rosters, and Historical Epidemiological baselines.
"""

# Master List of NLEM Medicines & Critical Medical Assets
NLEM_MEDICINES = [
    {
        "id": "MED-01",
        "name": "Paracetamol 500mg Tablets",
        "generic": "Paracetamol",
        "category": "Antipyretic / Analgesic",
        "unit": "Tablets",
        "cold_chain": False,
        "criticality": "HIGH",
        "standard_pack_size": 1000,
        "nlem_status": "Essential Class A"
    },
    {
        "id": "MED-02",
        "name": "Amoxicillin 500mg Capsules",
        "generic": "Amoxicillin",
        "category": "Antibiotic (Penicillin class)",
        "unit": "Capsules",
        "cold_chain": False,
        "criticality": "HIGH",
        "standard_pack_size": 500,
        "nlem_status": "Essential Class A"
    },
    {
        "id": "MED-03",
        "name": "ORS (Oral Rehydration Salts) 21.8g",
        "generic": "WHO-Formula ORS",
        "category": "Electrolyte Solution / Dehydration",
        "unit": "Sachets",
        "cold_chain": False,
        "criticality": "CRITICAL",
        "standard_pack_size": 500,
        "nlem_status": "Essential Class A"
    },
    {
        "id": "MED-04",
        "name": "Anti-Snake Venom (ASV) Lyophilized",
        "generic": "Polyvalent Snake Antivenom",
        "category": "Emergency Antidote / Toxin Neutralizer",
        "unit": "Vials (10ml)",
        "cold_chain": True,
        "min_temp_c": 2.0,
        "max_temp_c": 8.0,
        "criticality": "LIFE_SAVING",
        "standard_pack_size": 20,
        "nlem_status": "Vital / Life-Saving"
    },
    {
        "id": "MED-05",
        "name": "Rabies Vaccine (ARV) 0.5ml",
        "generic": "Purified Vero Cell Rabies Vaccine",
        "category": "Post-Exposure Prophylaxis Vaccine",
        "unit": "Doses/Vials",
        "cold_chain": True,
        "min_temp_c": 2.0,
        "max_temp_c": 8.0,
        "criticality": "LIFE_SAVING",
        "standard_pack_size": 50,
        "nlem_status": "Vital / Life-Saving"
    },
    {
        "id": "MED-06",
        "name": "Artemether + Lumefantrine (ACT)",
        "generic": "Artemether 20mg + Lumefantrine 120mg",
        "category": "Antimalarial First-Line",
        "unit": "Strips (6x4)",
        "cold_chain": False,
        "criticality": "HIGH",
        "standard_pack_size": 100,
        "nlem_status": "Essential Class A"
    },
    {
        "id": "MED-07",
        "name": "Oxytocin Injection 5 IU/ml",
        "generic": "Oxytocin",
        "category": "Uterotonic (Maternal Hemorrhage)",
        "unit": "Ampoules",
        "cold_chain": True,
        "min_temp_c": 2.0,
        "max_temp_c": 8.0,
        "criticality": "LIFE_SAVING",
        "standard_pack_size": 100,
        "nlem_status": "Vital / Maternal Health"
    },
    {
        "id": "MED-08",
        "name": "Human Insulin (Regular) 100 IU/ml",
        "generic": "Soluble Insulin",
        "category": "Diabetes Critical Glycemic Control",
        "unit": "Vials (10ml)",
        "cold_chain": True,
        "min_temp_c": 2.0,
        "max_temp_c": 8.0,
        "criticality": "LIFE_SAVING",
        "standard_pack_size": 50,
        "nlem_status": "Essential Class A"
    },
    {
        "id": "MED-09",
        "name": "Ceftriaxone 1g Injection",
        "generic": "Ceftriaxone Sodium",
        "category": "Broad Cephalosporin Antibiotic",
        "unit": "Vials",
        "cold_chain": False,
        "criticality": "HIGH",
        "standard_pack_size": 100,
        "nlem_status": "Essential Class A"
    },
    {
        "id": "MED-10",
        "name": "Dextrose Normal Saline (DNS 5%)",
        "generic": "Dextrose 5% + Sodium Chloride 0.9%",
        "category": "Resuscitation Intravenous Fluids",
        "unit": "Bottles (500ml)",
        "cold_chain": False,
        "criticality": "CRITICAL",
        "standard_pack_size": 200,
        "nlem_status": "Essential Class A"
    },
    {
        "id": "MED-11",
        "name": "Salbutamol Inhaler 100mcg",
        "generic": "Salbutamol Sulfate",
        "category": "Bronchodilator (Asthma/COPD/Respiratory)",
        "unit": "Canisters (200 puffs)",
        "cold_chain": False,
        "criticality": "HIGH",
        "standard_pack_size": 50,
        "nlem_status": "Essential Class B"
    },
    {
        "id": "MED-12",
        "name": "Zinc Sulfate 20mg Dispersible",
        "generic": "Zinc Sulfate",
        "category": "Pediatric Diarrhea Management",
        "unit": "Tablets",
        "cold_chain": False,
        "criticality": "HIGH",
        "standard_pack_size": 1000,
        "nlem_status": "Essential Class B"
    },
    {
        "id": "SUP-01",
        "name": "Medical Oxygen Cylinder (Type D)",
        "generic": "Compressed Medical Oxygen 46.7L",
        "category": "Respiratory Life Support",
        "unit": "Cylinders",
        "cold_chain": False,
        "criticality": "LIFE_SAVING",
        "standard_pack_size": 10,
        "nlem_status": "Vital Infrastructure"
    },
    {
        "id": "SUP-02",
        "name": "Rapid Dengue NS1/IgM/IgG Test Kit",
        "generic": "Immunochromatographic Diagnostic Kit",
        "category": "Vector-Borne Diagnostics",
        "unit": "Cassette Tests",
        "cold_chain": False,
        "criticality": "HIGH",
        "standard_pack_size": 100,
        "nlem_status": "Diagnostic Essential"
    },
    {
        "id": "SUP-03",
        "name": "Packed Red Blood Cells (PRBC)",
        "generic": "Whole Blood Component",
        "category": "Blood Transfusion Asset",
        "unit": "Bags (350ml)",
        "cold_chain": True,
        "min_temp_c": 2.0,
        "max_temp_c": 6.0,
        "criticality": "LIFE_SAVING",
        "standard_pack_size": 10,
        "nlem_status": "Vital / Life-Saving"
    }
]

# ALL 36 Indian States and Union Territories (28 States + 8 UTs)
STATES = [
    # --- 28 STATES ---
    {
        "code": "AP",
        "name": "Andhra Pradesh",
        "capital": "Amaravati",
        "lat": 16.5417,
        "lng": 80.5158,
        "zone": "South",
        "phc_network_count": 1145,
        "population_millions": 53.2,
        "monsoon_vulnerability": "CYCLONE_COASTAL_FEVER",
        "model_convergence_score": 0.952
    },
    {
        "code": "AR",
        "name": "Arunachal Pradesh",
        "capital": "Itanagar",
        "lat": 27.0844,
        "lng": 93.6053,
        "zone": "Northeast",
        "phc_network_count": 143,
        "population_millions": 1.6,
        "monsoon_vulnerability": "HILL_LANDSLIDE_MALARIA",
        "model_convergence_score": 0.908
    },
    {
        "code": "AS",
        "name": "Assam",
        "capital": "Guwahati / Dispur",
        "lat": 26.1445,
        "lng": 91.7362,
        "zone": "Northeast",
        "phc_network_count": 1014,
        "population_millions": 36.5,
        "monsoon_vulnerability": "EXTREME_BRAHMAPUTRA_FLOOD",
        "model_convergence_score": 0.914
    },
    {
        "code": "BR",
        "name": "Bihar",
        "capital": "Patna",
        "lat": 25.5941,
        "lng": 85.1376,
        "zone": "East",
        "phc_network_count": 1899,
        "population_millions": 128.0,
        "monsoon_vulnerability": "RIVERINE_FLOOD_GASTRO",
        "model_convergence_score": 0.932
    },
    {
        "code": "CG",
        "name": "Chhattisgarh",
        "capital": "Raipur",
        "lat": 21.2514,
        "lng": 81.6296,
        "zone": "Central",
        "phc_network_count": 792,
        "population_millions": 30.1,
        "monsoon_vulnerability": "TRIBAL_MALARIA_SNAKEBITE",
        "model_convergence_score": 0.928
    },
    {
        "code": "GA",
        "name": "Goa",
        "capital": "Panaji",
        "lat": 15.4909,
        "lng": 73.8278,
        "zone": "West",
        "phc_network_count": 24,
        "population_millions": 1.5,
        "monsoon_vulnerability": "COASTAL_LEPTOSPIROSIS",
        "model_convergence_score": 0.974
    },
    {
        "code": "GJ",
        "name": "Gujarat",
        "capital": "Gandhinagar",
        "lat": 23.2156,
        "lng": 72.6369,
        "zone": "West",
        "phc_network_count": 1476,
        "population_millions": 71.5,
        "monsoon_vulnerability": "URBAN_DENGUE_CHIKUNGUNYA",
        "model_convergence_score": 0.965
    },
    {
        "code": "HR",
        "name": "Haryana",
        "capital": "Chandigarh",
        "lat": 29.0588,
        "lng": 76.0856,
        "zone": "North",
        "phc_network_count": 536,
        "population_millions": 28.2,
        "monsoon_vulnerability": "PERI_URBAN_VECTOR_SURGE",
        "model_convergence_score": 0.961
    },
    {
        "code": "HP",
        "name": "Himachal Pradesh",
        "capital": "Shimla",
        "lat": 31.1048,
        "lng": 77.1734,
        "zone": "North",
        "phc_network_count": 586,
        "population_millions": 7.4,
        "monsoon_vulnerability": "SCRUB_TYPHUS_COLD_CHAIN",
        "model_convergence_score": 0.945
    },
    {
        "code": "JH",
        "name": "Jharkhand",
        "capital": "Ranchi",
        "lat": 23.3441,
        "lng": 85.3096,
        "zone": "East",
        "phc_network_count": 330,
        "population_millions": 39.4,
        "monsoon_vulnerability": "MALARIA_WATERBORNE",
        "model_convergence_score": 0.921
    },
    {
        "code": "KA",
        "name": "Karnataka",
        "capital": "Bengaluru",
        "lat": 12.9716,
        "lng": 77.5946,
        "zone": "South",
        "phc_network_count": 2359,
        "population_millions": 67.8,
        "monsoon_vulnerability": "KYASANUR_FOREST_DENGUE",
        "model_convergence_score": 0.972
    },
    {
        "code": "KL",
        "name": "Kerala",
        "capital": "Thiruvananthapuram",
        "lat": 10.8505,
        "lng": 76.2711,
        "zone": "South",
        "phc_network_count": 910,
        "population_millions": 35.8,
        "monsoon_vulnerability": "SEVERE_LEPTOSPIROSIS_FEVER",
        "model_convergence_score": 0.985
    },
    {
        "code": "MP",
        "name": "Madhya Pradesh",
        "capital": "Bhopal",
        "lat": 23.2599,
        "lng": 77.4126,
        "zone": "Central",
        "phc_network_count": 1412,
        "population_millions": 85.5,
        "monsoon_vulnerability": "MALNUTRITION_DIARRHEA_SURGE",
        "model_convergence_score": 0.936
    },
    {
        "code": "MH",
        "name": "Maharashtra",
        "capital": "Mumbai",
        "lat": 19.0760,
        "lng": 72.8777,
        "zone": "West",
        "phc_network_count": 1814,
        "population_millions": 126.0,
        "monsoon_vulnerability": "SEVERE_URBAN_DENGUE",
        "model_convergence_score": 0.968
    },
    {
        "code": "MN",
        "name": "Manipur",
        "capital": "Imphal",
        "lat": 24.8170,
        "lng": 93.9368,
        "zone": "Northeast",
        "phc_network_count": 95,
        "population_millions": 3.2,
        "monsoon_vulnerability": "REMOTE_SUPPLY_BOTTLENECK",
        "model_convergence_score": 0.912
    },
    {
        "code": "ML",
        "name": "Meghalaya",
        "capital": "Shillong",
        "lat": 25.5788,
        "lng": 91.8933,
        "zone": "Northeast",
        "phc_network_count": 144,
        "population_millions": 3.4,
        "monsoon_vulnerability": "HIGH_RAINFALL_ISOLATION",
        "model_convergence_score": 0.916
    },
    {
        "code": "MZ",
        "name": "Mizoram",
        "capital": "Aizawl",
        "lat": 23.7271,
        "lng": 92.7176,
        "zone": "Northeast",
        "phc_network_count": 65,
        "population_millions": 1.2,
        "monsoon_vulnerability": "FALCIPARUM_MALARIA",
        "model_convergence_score": 0.910
    },
    {
        "code": "NL",
        "name": "Nagaland",
        "capital": "Kohima",
        "lat": 25.6751,
        "lng": 94.1086,
        "zone": "Northeast",
        "phc_network_count": 140,
        "population_millions": 2.2,
        "monsoon_vulnerability": "TERRAIN_COLD_CHAIN_RISK",
        "model_convergence_score": 0.905
    },
    {
        "code": "OD",
        "name": "Odisha",
        "capital": "Bhubaneswar",
        "lat": 20.2961,
        "lng": 85.8245,
        "zone": "East",
        "phc_network_count": 1288,
        "population_millions": 46.2,
        "monsoon_vulnerability": "CYCLONE_COASTAL_WATERBORNE",
        "model_convergence_score": 0.938
    },
    {
        "code": "PB",
        "name": "Punjab",
        "capital": "Chandigarh",
        "lat": 31.1471,
        "lng": 75.3412,
        "zone": "North",
        "phc_network_count": 416,
        "population_millions": 30.7,
        "monsoon_vulnerability": "CANAL_MOSQUITO_SPIKE",
        "model_convergence_score": 0.963
    },
    {
        "code": "RJ",
        "name": "Rajasthan",
        "capital": "Jaipur",
        "lat": 26.9124,
        "lng": 75.7873,
        "zone": "Northwest",
        "phc_network_count": 2082,
        "population_millions": 81.0,
        "monsoon_vulnerability": "ARID_HEATWAVE_SCORPION",
        "model_convergence_score": 0.925
    },
    {
        "code": "SK",
        "name": "Sikkim",
        "capital": "Gangtok",
        "lat": 27.3389,
        "lng": 88.6065,
        "zone": "East",
        "phc_network_count": 24,
        "population_millions": 0.7,
        "monsoon_vulnerability": "HIGH_ALTITUDE_DISRUPTIONS",
        "model_convergence_score": 0.955
    },
    {
        "code": "TN",
        "name": "Tamil Nadu",
        "capital": "Chennai",
        "lat": 13.0827,
        "lng": 80.2707,
        "zone": "South",
        "phc_network_count": 1740,
        "population_millions": 76.9,
        "monsoon_vulnerability": "NORTHEAST_MONSOON_EPIDEMIC",
        "model_convergence_score": 0.979
    },
    {
        "code": "TG",
        "name": "Telangana",
        "capital": "Hyderabad",
        "lat": 17.3850,
        "lng": 78.4867,
        "zone": "South",
        "phc_network_count": 863,
        "population_millions": 38.0,
        "monsoon_vulnerability": "DECCAN_SEASONAL_VIRAL_FEVER",
        "model_convergence_score": 0.967
    },
    {
        "code": "TR",
        "name": "Tripura",
        "capital": "Agartala",
        "lat": 23.8315,
        "lng": 91.2868,
        "zone": "Northeast",
        "phc_network_count": 118,
        "population_millions": 4.1,
        "monsoon_vulnerability": "BORDER_EPIDEMIC_SURVEILLANCE",
        "model_convergence_score": 0.919
    },
    {
        "code": "UP",
        "name": "Uttar Pradesh",
        "capital": "Lucknow",
        "lat": 26.8467,
        "lng": 80.9462,
        "zone": "North",
        "phc_network_count": 3621,
        "population_millions": 241.0,
        "monsoon_vulnerability": "HIGH_FLOOD_RIVERINE",
        "model_convergence_score": 0.942
    },
    {
        "code": "UK",
        "name": "Uttarakhand",
        "capital": "Dehradun",
        "lat": 30.3165,
        "lng": 78.0322,
        "zone": "North",
        "phc_network_count": 257,
        "population_millions": 11.5,
        "monsoon_vulnerability": "PILGRIMAGE_HILL_EMERGENCIES",
        "model_convergence_score": 0.948
    },
    {
        "code": "WB",
        "name": "West Bengal",
        "capital": "Kolkata",
        "lat": 22.5726,
        "lng": 88.3639,
        "zone": "East",
        "phc_network_count": 1420,
        "population_millions": 99.1,
        "monsoon_vulnerability": "DELTIC_WATERBORNE_DENGUE",
        "model_convergence_score": 0.951
    },

    # --- 8 UNION TERRITORIES ---
    {
        "code": "AN",
        "name": "Andaman and Nicobar Islands",
        "capital": "Port Blair",
        "lat": 11.6234,
        "lng": 92.7265,
        "zone": "Islands",
        "phc_network_count": 22,
        "population_millions": 0.4,
        "monsoon_vulnerability": "ISLAND_SEA_ROTE_COLD_CHAIN",
        "model_convergence_score": 0.920
    },
    {
        "code": "CH",
        "name": "Chandigarh",
        "capital": "Chandigarh",
        "lat": 30.7333,
        "lng": 76.7794,
        "zone": "North",
        "phc_network_count": 38,
        "population_millions": 1.2,
        "monsoon_vulnerability": "URBAN_SEASONAL_INFLUENZA",
        "model_convergence_score": 0.988
    },
    {
        "code": "DN",
        "name": "Dadra and Nagar Haveli and Daman and Diu",
        "capital": "Daman",
        "lat": 20.3974,
        "lng": 72.8328,
        "zone": "West",
        "phc_network_count": 16,
        "population_millions": 0.6,
        "monsoon_vulnerability": "COASTAL_INDUSTRIAL_MIGRANT",
        "model_convergence_score": 0.949
    },
    {
        "code": "DL",
        "name": "Delhi",
        "capital": "New Delhi",
        "lat": 28.6139,
        "lng": 77.2090,
        "zone": "North",
        "phc_network_count": 520,
        "population_millions": 20.8,
        "monsoon_vulnerability": "HIGH_DENSITY_URBAN_DENGUE",
        "model_convergence_score": 0.991
    },
    {
        "code": "JK",
        "name": "Jammu and Kashmir",
        "capital": "Srinagar / Jammu",
        "lat": 34.0837,
        "lng": 74.7973,
        "zone": "North",
        "phc_network_count": 637,
        "population_millions": 13.6,
        "monsoon_vulnerability": "WINTER_ISOLATION_AVALANCHE",
        "model_convergence_score": 0.937
    },
    {
        "code": "LA",
        "name": "Ladakh",
        "capital": "Leh",
        "lat": 34.1526,
        "lng": 77.5771,
        "zone": "North",
        "phc_network_count": 35,
        "population_millions": 0.3,
        "monsoon_vulnerability": "EXTREME_COLD_ALTITUDE_HYPOXIA",
        "model_convergence_score": 0.898
    },
    {
        "code": "LD",
        "name": "Lakshadweep",
        "capital": "Kavaratti",
        "lat": 10.5667,
        "lng": 72.6417,
        "zone": "Islands",
        "phc_network_count": 9,
        "population_millions": 0.07,
        "monsoon_vulnerability": "ISOLATED_ATOLL_AIRLIFT_RELY",
        "model_convergence_score": 0.915
    },
    {
        "code": "PY",
        "name": "Puducherry",
        "capital": "Puducherry",
        "lat": 11.9416,
        "lng": 79.8083,
        "zone": "South",
        "phc_network_count": 40,
        "population_millions": 1.4,
        "monsoon_vulnerability": "COASTAL_POST_MONSOON_VIRAL",
        "model_convergence_score": 0.980
    }
]

# Granular Health Facilities (PHCs, CHCs, DHs) across ALL 36 States & UTs
FACILITIES = [
    # ==================== ANDHRA PRADESH ====================
    {
        "id": "AP-GUN-001",
        "name": "PHC Mangalagiri",
        "type": "PHC",
        "state_code": "AP",
        "district": "Guntur",
        "lat": 16.4300,
        "lng": 80.5600,
        "pincode": "522503",
        "catchment_population": 36000,
        "medical_officer_in_charge": "Dr. K. Radhakrishna",
        "contact_phone": "+91 94401 21001",
        "tier": "Rural Primary",
        "power_backup_hours": 16,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "AP-GUN-002",
        "name": "CHC Tenali",
        "type": "CHC",
        "state_code": "AP",
        "district": "Guntur",
        "lat": 16.2430,
        "lng": 80.6400,
        "pincode": "522201",
        "catchment_population": 95000,
        "medical_officer_in_charge": "Dr. S. Lakshmi",
        "contact_phone": "+91 94401 21002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "AP-KRI-001",
        "name": "District Hospital Machilipatnam",
        "type": "DH",
        "state_code": "AP",
        "district": "Krishna",
        "lat": 16.1809,
        "lng": 81.1303,
        "pincode": "521001",
        "catchment_population": 420000,
        "medical_officer_in_charge": "Dr. P. Venkata Rao",
        "contact_phone": "+91 94401 21003",
        "tier": "Apex District Tertiary Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== ARUNACHAL PRADESH ====================
    {
        "id": "AR-PAP-001",
        "name": "PHC Doimukh",
        "type": "PHC",
        "state_code": "AR",
        "district": "Papum Pare",
        "lat": 27.1400,
        "lng": 93.7500,
        "pincode": "791112",
        "catchment_population": 18500,
        "medical_officer_in_charge": "Dr. Taba Taku",
        "contact_phone": "+91 94360 41001",
        "tier": "Hill Terrain Primary",
        "power_backup_hours": 20,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "AR-PAP-002",
        "name": "CHC Sagalee",
        "type": "CHC",
        "state_code": "AR",
        "district": "Papum Pare",
        "lat": 27.2400,
        "lng": 93.3500,
        "pincode": "791112",
        "catchment_population": 32000,
        "medical_officer_in_charge": "Dr. Nabam Joram",
        "contact_phone": "+91 94360 41002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "AR-PAP-003",
        "name": "TRIHMS District Apex Hospital Naharlagun",
        "type": "DH",
        "state_code": "AR",
        "district": "Papum Pare",
        "lat": 27.1064,
        "lng": 93.6937,
        "pincode": "791110",
        "catchment_population": 180000,
        "medical_officer_in_charge": "Dr. Moji Jini",
        "contact_phone": "+91 94360 41003",
        "tier": "Apex State Referral Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== ASSAM ====================
    {
        "id": "AS-KAM-001",
        "name": "PHC Hajo",
        "type": "PHC",
        "state_code": "AS",
        "district": "Kamrup Rural",
        "lat": 26.2472,
        "lng": 91.5284,
        "pincode": "781102",
        "catchment_population": 31000,
        "medical_officer_in_charge": "Dr. Bhaben Kalita",
        "contact_phone": "+91 94350 31001",
        "tier": "Flood-Prone Rural Primary",
        "power_backup_hours": 18,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "AS-KAM-002",
        "name": "PHC Sualkuchi",
        "type": "PHC",
        "state_code": "AS",
        "district": "Kamrup Rural",
        "lat": 26.1712,
        "lng": 91.5721,
        "pincode": "781103",
        "catchment_population": 28000,
        "medical_officer_in_charge": "Dr. Moushumi Baruah",
        "contact_phone": "+91 94350 31002",
        "tier": "Rural Primary",
        "power_backup_hours": 12,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:48:00Z"
    },
    {
        "id": "AS-KAM-003",
        "name": "CHC Rangia",
        "type": "CHC",
        "state_code": "AS",
        "district": "Kamrup Rural",
        "lat": 26.4682,
        "lng": 91.6315,
        "pincode": "781354",
        "catchment_population": 86000,
        "medical_officer_in_charge": "Dr. Dhrubajyoti Deka",
        "contact_phone": "+91 94350 31003",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:52:00Z"
    },
    {
        "id": "AS-GHY-001",
        "name": "Gauhati Medical College & District Apex Hospital",
        "type": "DH",
        "state_code": "AS",
        "district": "Kamrup Metro",
        "lat": 26.1584,
        "lng": 91.7744,
        "pincode": "781032",
        "catchment_population": 850000,
        "medical_officer_in_charge": "Dr. Abhijit Sarma",
        "contact_phone": "+91 94350 31004",
        "tier": "Apex State Referral & Teaching Hub",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:58:00Z"
    },

    # ==================== BIHAR ====================
    {
        "id": "BR-PAT-001",
        "name": "PHC Phulwari Sharif",
        "type": "PHC",
        "state_code": "BR",
        "district": "Patna",
        "lat": 25.5780,
        "lng": 85.0760,
        "pincode": "801505",
        "catchment_population": 48000,
        "medical_officer_in_charge": "Dr. Sanjay Kumar Sinha",
        "contact_phone": "+91 94310 11001",
        "tier": "Peri-Urban Primary",
        "power_backup_hours": 14,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "BR-PAT-002",
        "name": "PHC Maner",
        "type": "PHC",
        "state_code": "BR",
        "district": "Patna",
        "lat": 25.6480,
        "lng": 84.8780,
        "pincode": "801108",
        "catchment_population": 39000,
        "medical_officer_in_charge": "Dr. Rakesh Ranjan",
        "contact_phone": "+91 94310 11002",
        "tier": "Riverine Rural Primary",
        "power_backup_hours": 12,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:48:00Z"
    },
    {
        "id": "BR-PAT-003",
        "name": "CHC Danapur",
        "type": "CHC",
        "state_code": "BR",
        "district": "Patna",
        "lat": 25.6300,
        "lng": 85.0400,
        "pincode": "801503",
        "catchment_population": 120000,
        "medical_officer_in_charge": "Dr. Anita Kumari",
        "contact_phone": "+91 94310 11003",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:52:00Z"
    },
    {
        "id": "BR-PAT-004",
        "name": "Patna Sadar District Hospital",
        "type": "DH",
        "state_code": "BR",
        "district": "Patna",
        "lat": 25.5975,
        "lng": 85.1235,
        "pincode": "800001",
        "catchment_population": 650000,
        "medical_officer_in_charge": "Dr. Pramod Kumar Jha",
        "contact_phone": "+91 94310 11004",
        "tier": "Apex District Tertiary Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:58:00Z"
    },

    # ==================== CHHATTISGARH ====================
    {
        "id": "CG-RAI-001",
        "name": "PHC Abhanpur",
        "type": "PHC",
        "state_code": "CG",
        "district": "Raipur",
        "lat": 21.0500,
        "lng": 81.7500,
        "pincode": "493661",
        "catchment_population": 32000,
        "medical_officer_in_charge": "Dr. Bhupendra Sahu",
        "contact_phone": "+91 94252 51001",
        "tier": "Rural Primary",
        "power_backup_hours": 16,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "CG-RAI-002",
        "name": "CHC Arang",
        "type": "CHC",
        "state_code": "CG",
        "district": "Raipur",
        "lat": 21.1900,
        "lng": 81.9700,
        "pincode": "493441",
        "catchment_population": 82000,
        "medical_officer_in_charge": "Dr. Madhuri Sharma",
        "contact_phone": "+91 94252 51002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "CG-RAI-003",
        "name": "Dr. B.R. Ambedkar Memorial District Hospital Raipur",
        "type": "DH",
        "state_code": "CG",
        "district": "Raipur",
        "lat": 21.2480,
        "lng": 81.6520,
        "pincode": "492001",
        "catchment_population": 720000,
        "medical_officer_in_charge": "Dr. Vineet Jain",
        "contact_phone": "+91 94252 51003",
        "tier": "Apex District Tertiary Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== GOA ====================
    {
        "id": "GA-NG-001",
        "name": "PHC Aldona",
        "type": "PHC",
        "state_code": "GA",
        "district": "North Goa",
        "lat": 15.5880,
        "lng": 73.8730,
        "pincode": "403508",
        "catchment_population": 22000,
        "medical_officer_in_charge": "Dr. Preetam Naik",
        "contact_phone": "+91 98221 61001",
        "tier": "Coastal Rural Primary",
        "power_backup_hours": 16,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "GA-NG-002",
        "name": "CHC Valpoi",
        "type": "CHC",
        "state_code": "GA",
        "district": "North Goa",
        "lat": 15.5300,
        "lng": 74.1300,
        "pincode": "403506",
        "catchment_population": 45000,
        "medical_officer_in_charge": "Dr. Gajanan Prabhu",
        "contact_phone": "+91 98221 61002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "GA-NG-003",
        "name": "North Goa District Hospital Mapusa",
        "type": "DH",
        "state_code": "GA",
        "district": "North Goa",
        "lat": 15.5930,
        "lng": 73.8150,
        "pincode": "403507",
        "catchment_population": 280000,
        "medical_officer_in_charge": "Dr. Geeta Kakodkar",
        "contact_phone": "+91 98221 61003",
        "tier": "Apex District Tertiary Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== GUJARAT ====================
    {
        "id": "GJ-GAN-001",
        "name": "PHC Mansa",
        "type": "PHC",
        "state_code": "GJ",
        "district": "Gandhinagar",
        "lat": 23.4260,
        "lng": 72.6610,
        "pincode": "382845",
        "catchment_population": 38000,
        "medical_officer_in_charge": "Dr. Nilesh Patel",
        "contact_phone": "+91 98250 71001",
        "tier": "Rural Primary",
        "power_backup_hours": 18,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "GJ-GAN-002",
        "name": "CHC Kalol",
        "type": "CHC",
        "state_code": "GJ",
        "district": "Gandhinagar",
        "lat": 23.2350,
        "lng": 72.4980,
        "pincode": "382721",
        "catchment_population": 110000,
        "medical_officer_in_charge": "Dr. Bhavna Shah",
        "contact_phone": "+91 98250 71002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "GJ-AHM-001",
        "name": "Civil Hospital & District Medical Center Ahmedabad",
        "type": "DH",
        "state_code": "GJ",
        "district": "Ahmedabad",
        "lat": 23.0525,
        "lng": 72.5972,
        "pincode": "380016",
        "catchment_population": 950000,
        "medical_officer_in_charge": "Dr. Rakesh Joshi",
        "contact_phone": "+91 98250 71003",
        "tier": "Apex Regional Teaching Hub & Depot",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:58:00Z"
    },

    # ==================== HARYANA ====================
    {
        "id": "HR-GUR-001",
        "name": "PHC Farrukhnagar",
        "type": "PHC",
        "state_code": "HR",
        "district": "Gurugram",
        "lat": 28.4500,
        "lng": 76.8200,
        "pincode": "122506",
        "catchment_population": 35000,
        "medical_officer_in_charge": "Dr. Sandeep Yadav",
        "contact_phone": "+91 94160 81001",
        "tier": "Rural Primary",
        "power_backup_hours": 16,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "HR-GUR-002",
        "name": "CHC Sohna",
        "type": "CHC",
        "state_code": "HR",
        "district": "Gurugram",
        "lat": 28.2500,
        "lng": 77.0600,
        "pincode": "122103",
        "catchment_population": 92000,
        "medical_officer_in_charge": "Dr. Meenakshi Singh",
        "contact_phone": "+91 94160 81002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "HR-GUR-003",
        "name": "Civil District Hospital Gurugram",
        "type": "DH",
        "state_code": "HR",
        "district": "Gurugram",
        "lat": 28.4600,
        "lng": 77.0300,
        "pincode": "122001",
        "catchment_population": 580000,
        "medical_officer_in_charge": "Dr. Virender Yadav",
        "contact_phone": "+91 94160 81003",
        "tier": "Apex District Tertiary Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== HIMACHAL PRADESH ====================
    {
        "id": "HP-SHI-001",
        "name": "PHC Mashobra",
        "type": "PHC",
        "state_code": "HP",
        "district": "Shimla",
        "lat": 31.1300,
        "lng": 77.2300,
        "pincode": "171007",
        "catchment_population": 19000,
        "medical_officer_in_charge": "Dr. Rohit Verma",
        "contact_phone": "+91 94180 91001",
        "tier": "Hill Primary",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "HP-SHI-002",
        "name": "CHC Theog",
        "type": "CHC",
        "state_code": "HP",
        "district": "Shimla",
        "lat": 31.1200,
        "lng": 77.3500,
        "pincode": "171201",
        "catchment_population": 42000,
        "medical_officer_in_charge": "Dr. Shalini Sharma",
        "contact_phone": "+91 94180 91002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 36,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "HP-SHI-003",
        "name": "DDU Zonal District Hospital Shimla",
        "type": "DH",
        "state_code": "HP",
        "district": "Shimla",
        "lat": 31.1040,
        "lng": 77.1680,
        "pincode": "171001",
        "catchment_population": 220000,
        "medical_officer_in_charge": "Dr. Surender Singh",
        "contact_phone": "+91 94180 91003",
        "tier": "Apex Zonal Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== JHARKHAND ====================
    {
        "id": "JH-RAN-001",
        "name": "PHC Kanke",
        "type": "PHC",
        "state_code": "JH",
        "district": "Ranchi",
        "lat": 23.4300,
        "lng": 85.3200,
        "pincode": "834006",
        "catchment_population": 38000,
        "medical_officer_in_charge": "Dr. Manish Tirkey",
        "contact_phone": "+91 94311 01001",
        "tier": "Rural Primary",
        "power_backup_hours": 16,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "JH-RAN-002",
        "name": "CHC Ormanjhi",
        "type": "CHC",
        "state_code": "JH",
        "district": "Ranchi",
        "lat": 23.4800,
        "lng": 85.4800,
        "pincode": "835219",
        "catchment_population": 88000,
        "medical_officer_in_charge": "Dr. Sunita Soren",
        "contact_phone": "+91 94311 01002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "JH-RAN-003",
        "name": "Sadar District Hospital Ranchi",
        "type": "DH",
        "state_code": "JH",
        "district": "Ranchi",
        "lat": 23.3650,
        "lng": 85.3260,
        "pincode": "834001",
        "catchment_population": 620000,
        "medical_officer_in_charge": "Dr. Vinod Kumar",
        "contact_phone": "+91 94311 01003",
        "tier": "Apex District Tertiary Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== KARNATAKA ====================
    {
        "id": "KA-BLR-001",
        "name": "UPHC Malleshwaram",
        "type": "PHC",
        "state_code": "KA",
        "district": "Bengaluru Urban",
        "lat": 13.0030,
        "lng": 77.5700,
        "pincode": "560003",
        "catchment_population": 46000,
        "medical_officer_in_charge": "Dr. Chethan Gowda",
        "contact_phone": "+91 94480 12001",
        "tier": "Urban Primary",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "KA-BLR-002",
        "name": "CHC Yelahanka",
        "type": "CHC",
        "state_code": "KA",
        "district": "Bengaluru Urban",
        "lat": 13.1007,
        "lng": 77.5963,
        "pincode": "560064",
        "catchment_population": 125000,
        "medical_officer_in_charge": "Dr. Archana Rao",
        "contact_phone": "+91 94480 12002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 36,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "KA-BLR-003",
        "name": "KC General District Hospital Malleshwaram",
        "type": "DH",
        "state_code": "KA",
        "district": "Bengaluru Urban",
        "lat": 12.9980,
        "lng": 77.5710,
        "pincode": "560003",
        "catchment_population": 740000,
        "medical_officer_in_charge": "Dr. B.R. Venkatesh",
        "contact_phone": "+91 94480 12003",
        "tier": "Apex District Tertiary Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== KERALA ====================
    {
        "id": "KL-EKM-001",
        "name": "PHC Cheranalloor (FHC)",
        "type": "PHC",
        "state_code": "KL",
        "district": "Ernakulam",
        "lat": 10.0543,
        "lng": 76.2891,
        "pincode": "682034",
        "catchment_population": 31000,
        "medical_officer_in_charge": "Dr. Sreejith Nair",
        "contact_phone": "+91 94470 51001",
        "tier": "Family Health Centre (Arogyam)",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "KL-EKM-002",
        "name": "PHC Mulavukad",
        "type": "PHC",
        "state_code": "KL",
        "district": "Ernakulam",
        "lat": 10.0084,
        "lng": 76.2625,
        "pincode": "682504",
        "catchment_population": 24000,
        "medical_officer_in_charge": "Dr. Anjali Menon",
        "contact_phone": "+91 94470 51002",
        "tier": "Island/Coastal Primary",
        "power_backup_hours": 18,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:48:00Z"
    },
    {
        "id": "KL-EKM-003",
        "name": "CHC Kalamassery",
        "type": "CHC",
        "state_code": "KL",
        "district": "Ernakulam",
        "lat": 10.0514,
        "lng": 76.3197,
        "pincode": "683104",
        "catchment_population": 78000,
        "medical_officer_in_charge": "Dr. Thomas K. Joseph",
        "contact_phone": "+91 94470 51003",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 36,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "KL-EKM-004",
        "name": "General Hospital Ernakulam",
        "type": "DH",
        "state_code": "KL",
        "district": "Ernakulam",
        "lat": 9.9726,
        "lng": 76.2811,
        "pincode": "682011",
        "catchment_population": 680000,
        "medical_officer_in_charge": "Dr. Shahirsha R.",
        "contact_phone": "+91 94470 51004",
        "tier": "Apex District General Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },
    {
        "id": "KL-KKD-001",
        "name": "Govt Medical College & Regional Hospital Kozhikode",
        "type": "DH",
        "state_code": "KL",
        "district": "Kozhikode",
        "lat": 11.2721,
        "lng": 75.8368,
        "pincode": "673008",
        "catchment_population": 810000,
        "medical_officer_in_charge": "Dr. S. Sankar",
        "contact_phone": "+91 94470 51005",
        "tier": "Apex Teaching Hospital & Regional Depot",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:58:00Z"
    },

    # ==================== MADHYA PRADESH ====================
    {
        "id": "MP-BHO-001",
        "name": "PHC Berasia",
        "type": "PHC",
        "state_code": "MP",
        "district": "Bhopal",
        "lat": 23.6300,
        "lng": 77.4300,
        "pincode": "463106",
        "catchment_population": 37000,
        "medical_officer_in_charge": "Dr. Alok Tripathi",
        "contact_phone": "+91 94250 22001",
        "tier": "Rural Primary",
        "power_backup_hours": 16,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "MP-BHO-002",
        "name": "CHC Phanda",
        "type": "CHC",
        "state_code": "MP",
        "district": "Bhopal",
        "lat": 23.2200,
        "lng": 77.2500,
        "pincode": "462030",
        "catchment_population": 89000,
        "medical_officer_in_charge": "Dr. Rashmi Chouhan",
        "contact_phone": "+91 94250 22002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "MP-BHO-003",
        "name": "Jayaprakash District Hospital Bhopal",
        "type": "DH",
        "state_code": "MP",
        "district": "Bhopal",
        "lat": 23.2250,
        "lng": 77.4200,
        "pincode": "462016",
        "catchment_population": 690000,
        "medical_officer_in_charge": "Dr. Rakesh Shrivastava",
        "contact_phone": "+91 94250 22003",
        "tier": "Apex District Tertiary Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== MAHARASHTRA ====================
    {
        "id": "MH-PUN-001",
        "name": "PHC Wagholi",
        "type": "PHC",
        "state_code": "MH",
        "district": "Pune",
        "lat": 18.5793,
        "lng": 73.9822,
        "pincode": "412207",
        "catchment_population": 44000,
        "medical_officer_in_charge": "Dr. Santosh Gaikwad",
        "contact_phone": "+91 98220 41001",
        "tier": "Peri-Urban Primary",
        "power_backup_hours": 18,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "MH-PUN-002",
        "name": "PHC Uruli Kanchan",
        "type": "PHC",
        "state_code": "MH",
        "district": "Pune",
        "lat": 18.4870,
        "lng": 74.1352,
        "pincode": "412202",
        "catchment_population": 38000,
        "medical_officer_in_charge": "Dr. Swati Deshmukh",
        "contact_phone": "+91 98220 41002",
        "tier": "Rural Primary",
        "power_backup_hours": 16,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:48:00Z"
    },
    {
        "id": "MH-PUN-003",
        "name": "CHC Shirur",
        "type": "CHC",
        "state_code": "MH",
        "district": "Pune",
        "lat": 18.8256,
        "lng": 74.3789,
        "pincode": "412210",
        "catchment_population": 96000,
        "medical_officer_in_charge": "Dr. Prakash Bhosale",
        "contact_phone": "+91 98220 41003",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "MH-PUN-004",
        "name": "District Hospital Aundh Pune",
        "type": "DH",
        "state_code": "MH",
        "district": "Pune",
        "lat": 18.5642,
        "lng": 73.8078,
        "pincode": "411027",
        "catchment_population": 710000,
        "medical_officer_in_charge": "Dr. Nagnath Yempalle",
        "contact_phone": "+91 98220 41004",
        "tier": "Apex District Tertiary Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },
    {
        "id": "MH-MUM-001",
        "name": "Grant Medical College & Sir JJ Group of Hospitals",
        "type": "DH",
        "state_code": "MH",
        "district": "Mumbai",
        "lat": 18.9634,
        "lng": 72.8339,
        "pincode": "400008",
        "catchment_population": 1100000,
        "medical_officer_in_charge": "Dr. Pallavi Saple",
        "contact_phone": "+91 98220 41005",
        "tier": "Apex Regional Teaching Hub & Depot",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:58:00Z"
    },

    # ==================== MANIPUR ====================
    {
        "id": "MN-IMP-001",
        "name": "PHC Sawombung",
        "type": "PHC",
        "state_code": "MN",
        "district": "Imphal East",
        "lat": 24.8500,
        "lng": 94.0200,
        "pincode": "795010",
        "catchment_population": 21000,
        "medical_officer_in_charge": "Dr. L. Tomba Singh",
        "contact_phone": "+91 94360 23001",
        "tier": "Rural Primary",
        "power_backup_hours": 18,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "MN-IMP-002",
        "name": "CHC Sagolmang",
        "type": "CHC",
        "state_code": "MN",
        "district": "Imphal East",
        "lat": 24.9300,
        "lng": 94.0500,
        "pincode": "795010",
        "catchment_population": 41000,
        "medical_officer_in_charge": "Dr. N. Bimol Devi",
        "contact_phone": "+91 94360 23002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "MN-IMP-003",
        "name": "JNIMS District Referral Hospital Porompat",
        "type": "DH",
        "state_code": "MN",
        "district": "Imphal East",
        "lat": 24.8150,
        "lng": 93.9550,
        "pincode": "795005",
        "catchment_population": 290000,
        "medical_officer_in_charge": "Dr. Kh. Lokeshwar",
        "contact_phone": "+91 94360 23003",
        "tier": "Apex State Referral Center",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== MEGHALAYA ====================
    {
        "id": "ML-EKH-001",
        "name": "PHC Mawphlang",
        "type": "PHC",
        "state_code": "ML",
        "district": "East Khasi Hills",
        "lat": 25.4500,
        "lng": 91.7600,
        "pincode": "793121",
        "catchment_population": 23000,
        "medical_officer_in_charge": "Dr. Banrida Kharbuli",
        "contact_phone": "+91 94361 14001",
        "tier": "Hill Terrain Primary",
        "power_backup_hours": 20,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "ML-EKH-002",
        "name": "CHC Cherrapunjee / Sohra",
        "type": "CHC",
        "state_code": "ML",
        "district": "East Khasi Hills",
        "lat": 25.2700,
        "lng": 91.7300,
        "pincode": "793108",
        "catchment_population": 48000,
        "medical_officer_in_charge": "Dr. Daniel Lyngdoh",
        "contact_phone": "+91 94361 14002",
        "tier": "High Rainfall Community Hospital",
        "power_backup_hours": 36,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "ML-EKH-003",
        "name": "Civil District Hospital Shillong",
        "type": "DH",
        "state_code": "ML",
        "district": "East Khasi Hills",
        "lat": 25.5720,
        "lng": 91.8820,
        "pincode": "793001",
        "catchment_population": 310000,
        "medical_officer_in_charge": "Dr. S.S. Nongbri",
        "contact_phone": "+91 94361 14003",
        "tier": "Apex State Referral Center",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== MIZORAM ====================
    {
        "id": "MZ-AIZ-001",
        "name": "PHC Darlawn",
        "type": "PHC",
        "state_code": "MZ",
        "district": "Aizawl",
        "lat": 24.0200,
        "lng": 92.9300,
        "pincode": "796111",
        "catchment_population": 17000,
        "medical_officer_in_charge": "Dr. Lalramliana",
        "contact_phone": "+91 94361 55001",
        "tier": "Hill Terrain Primary",
        "power_backup_hours": 20,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "MZ-AIZ-002",
        "name": "CHC Thingsulthliah",
        "type": "CHC",
        "state_code": "MZ",
        "district": "Aizawl",
        "lat": 23.6700,
        "lng": 92.8800,
        "pincode": "796161",
        "catchment_population": 36000,
        "medical_officer_in_charge": "Dr. C. Lalthanzami",
        "contact_phone": "+91 94361 55002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "MZ-AIZ-003",
        "name": "Aizawl Civil District Hospital",
        "type": "DH",
        "state_code": "MZ",
        "district": "Aizawl",
        "lat": 23.7310,
        "lng": 92.7180,
        "pincode": "796001",
        "catchment_population": 270000,
        "medical_officer_in_charge": "Dr. R. Lalthangliana",
        "contact_phone": "+91 94361 55003",
        "tier": "Apex State Referral Center",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== NAGALAND ====================
    {
        "id": "NL-KOH-001",
        "name": "PHC Jakhama",
        "type": "PHC",
        "state_code": "NL",
        "district": "Kohima",
        "lat": 25.5900,
        "lng": 94.1300,
        "pincode": "797005",
        "catchment_population": 19000,
        "medical_officer_in_charge": "Dr. Kevichusa Angami",
        "contact_phone": "+91 94360 66001",
        "tier": "Hill Primary",
        "power_backup_hours": 20,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "NL-KOH-002",
        "name": "CHC Chiephobozou",
        "type": "CHC",
        "state_code": "NL",
        "district": "Kohima",
        "lat": 25.7800,
        "lng": 94.1500,
        "pincode": "797105",
        "catchment_population": 38000,
        "medical_officer_in_charge": "Dr. Arenla Jamir",
        "contact_phone": "+91 94360 66002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "NL-KOH-003",
        "name": "Naga Hospital Authority District Apex Center Kohima",
        "type": "DH",
        "state_code": "NL",
        "district": "Kohima",
        "lat": 25.6690,
        "lng": 94.1040,
        "pincode": "797001",
        "catchment_population": 240000,
        "medical_officer_in_charge": "Dr. Sendimeren Aier",
        "contact_phone": "+91 94360 66003",
        "tier": "Apex State Referral Center",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== ODISHA ====================
    {
        "id": "OD-KHO-001",
        "name": "PHC Balianta",
        "type": "PHC",
        "state_code": "OD",
        "district": "Khordha",
        "lat": 20.2831,
        "lng": 85.8821,
        "pincode": "752101",
        "catchment_population": 29000,
        "medical_officer_in_charge": "Dr. Subhashree Mohanty",
        "contact_phone": "+91 94370 71001",
        "tier": "Rural Primary",
        "power_backup_hours": 18,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "OD-KHO-002",
        "name": "PHC Jatni",
        "type": "PHC",
        "state_code": "OD",
        "district": "Khordha",
        "lat": 20.1610,
        "lng": 85.7062,
        "pincode": "752050",
        "catchment_population": 35000,
        "medical_officer_in_charge": "Dr. Debasish Nayak",
        "contact_phone": "+91 94370 71002",
        "tier": "Peri-Urban Primary",
        "power_backup_hours": 16,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:48:00Z"
    },
    {
        "id": "OD-PUR-001",
        "name": "CHC Pipili",
        "type": "CHC",
        "state_code": "OD",
        "district": "Puri",
        "lat": 20.1165,
        "lng": 85.8322,
        "pincode": "752104",
        "catchment_population": 87000,
        "medical_officer_in_charge": "Dr. Saroj Kanta Mishra",
        "contact_phone": "+91 94370 71003",
        "tier": "Cyclone Shelter & Community Hospital",
        "power_backup_hours": 36,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "OD-KHO-003",
        "name": "Capital Hospital Bhubaneswar",
        "type": "DH",
        "state_code": "OD",
        "district": "Khordha",
        "lat": 20.2644,
        "lng": 85.8281,
        "pincode": "751001",
        "catchment_population": 680000,
        "medical_officer_in_charge": "Dr. Laxmidhar Sahoo",
        "contact_phone": "+91 94370 71004",
        "tier": "Apex Capital Tertiary Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },
    {
        "id": "OD-PUR-002",
        "name": "District Headquarters Hospital Puri",
        "type": "DH",
        "state_code": "OD",
        "district": "Puri",
        "lat": 19.8135,
        "lng": 85.8312,
        "pincode": "752001",
        "catchment_population": 410000,
        "medical_officer_in_charge": "Dr. Pranab Shankar Das",
        "contact_phone": "+91 94370 71005",
        "tier": "Coastal District Apex Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:58:00Z"
    },

    # ==================== PUNJAB ====================
    {
        "id": "PB-SAS-001",
        "name": "PHC Majri",
        "type": "PHC",
        "state_code": "PB",
        "district": "SAS Nagar (Mohali)",
        "lat": 30.8200,
        "lng": 76.7100,
        "pincode": "140110",
        "catchment_population": 34000,
        "medical_officer_in_charge": "Dr. Gurpreet Singh",
        "contact_phone": "+91 98140 18001",
        "tier": "Rural Primary",
        "power_backup_hours": 18,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "PB-SAS-002",
        "name": "CHC Kharar",
        "type": "CHC",
        "state_code": "PB",
        "district": "SAS Nagar (Mohali)",
        "lat": 30.7450,
        "lng": 76.6450,
        "pincode": "140301",
        "catchment_population": 94000,
        "medical_officer_in_charge": "Dr. Manjit Kaur",
        "contact_phone": "+91 98140 18002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "PB-SAS-003",
        "name": "Civil District Hospital Phase 6 Mohali",
        "type": "DH",
        "state_code": "PB",
        "district": "SAS Nagar (Mohali)",
        "lat": 30.7200,
        "lng": 76.7100,
        "pincode": "160055",
        "catchment_population": 490000,
        "medical_officer_in_charge": "Dr. Adarshpal Kaur",
        "contact_phone": "+91 98140 18003",
        "tier": "Apex District Tertiary Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== RAJASTHAN ====================
    {
        "id": "RJ-JAI-001",
        "name": "PHC Bassi",
        "type": "PHC",
        "state_code": "RJ",
        "district": "Jaipur",
        "lat": 26.8321,
        "lng": 76.0450,
        "pincode": "303301",
        "catchment_population": 36000,
        "medical_officer_in_charge": "Dr. Surendra Sharma",
        "contact_phone": "+91 94140 61001",
        "tier": "Rural Primary",
        "power_backup_hours": 16,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "RJ-JAI-002",
        "name": "PHC Chaksu",
        "type": "PHC",
        "state_code": "RJ",
        "district": "Jaipur",
        "lat": 26.6025,
        "lng": 75.9520,
        "pincode": "303901",
        "catchment_population": 33000,
        "medical_officer_in_charge": "Dr. Sunita Meena",
        "contact_phone": "+91 94140 61002",
        "tier": "Rural Primary",
        "power_backup_hours": 14,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:48:00Z"
    },
    {
        "id": "RJ-JAI-003",
        "name": "CHC Chomu",
        "type": "CHC",
        "state_code": "RJ",
        "district": "Jaipur",
        "lat": 27.1720,
        "lng": 75.7230,
        "pincode": "303702",
        "catchment_population": 98000,
        "medical_officer_in_charge": "Dr. Ramavtar Choudhary",
        "contact_phone": "+91 94140 61003",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "RJ-JAI-004",
        "name": "Sawai Man Singh (SMS) Medical College & Hospital",
        "type": "DH",
        "state_code": "RJ",
        "district": "Jaipur",
        "lat": 26.8988,
        "lng": 75.8175,
        "pincode": "302004",
        "catchment_population": 1200000,
        "medical_officer_in_charge": "Dr. Rajeev Bagarhatta",
        "contact_phone": "+91 94140 61004",
        "tier": "Apex Regional Teaching Hub & Depot",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },
    {
        "id": "RJ-JOD-001",
        "name": "Mathura Das Mathur District Referral Hospital Jodhpur",
        "type": "DH",
        "state_code": "RJ",
        "district": "Jodhpur",
        "lat": 26.2625,
        "lng": 73.0130,
        "pincode": "342003",
        "catchment_population": 650000,
        "medical_officer_in_charge": "Dr. M.K. Aseri",
        "contact_phone": "+91 94140 61005",
        "tier": "Arid Zone Apex District Center",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:58:00Z"
    },

    # ==================== SIKKIM ====================
    {
        "id": "SK-ES-001",
        "name": "PHC Singtam",
        "type": "PHC",
        "state_code": "SK",
        "district": "East Sikkim",
        "lat": 27.2300,
        "lng": 88.5000,
        "pincode": "737134",
        "catchment_population": 16000,
        "medical_officer_in_charge": "Dr. Karma Bhutia",
        "contact_phone": "+91 94340 77001",
        "tier": "Highland Primary",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "SK-ES-002",
        "name": "CHC Rangpo",
        "type": "CHC",
        "state_code": "SK",
        "district": "East Sikkim",
        "lat": 27.1800,
        "lng": 88.5300,
        "pincode": "737132",
        "catchment_population": 32000,
        "medical_officer_in_charge": "Dr. Doma Lepcha",
        "contact_phone": "+91 94340 77002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 36,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "SK-ES-003",
        "name": "STNM Central Referral District Hospital Gangtok",
        "type": "DH",
        "state_code": "SK",
        "district": "East Sikkim",
        "lat": 27.3250,
        "lng": 88.6120,
        "pincode": "737101",
        "catchment_population": 190000,
        "medical_officer_in_charge": "Dr. K.B. Gurung",
        "contact_phone": "+91 94340 77003",
        "tier": "Apex State Referral Center",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== TAMIL NADU ====================
    {
        "id": "TN-MAD-001",
        "name": "PHC Alanganallur",
        "type": "PHC",
        "state_code": "TN",
        "district": "Madurai",
        "lat": 10.0425,
        "lng": 78.0934,
        "pincode": "625501",
        "catchment_population": 29000,
        "medical_officer_in_charge": "Dr. M. Senthamizhan",
        "contact_phone": "+91 94430 81001",
        "tier": "Rural Primary",
        "power_backup_hours": 18,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "TN-MAD-002",
        "name": "PHC Samayanallur",
        "type": "PHC",
        "state_code": "TN",
        "district": "Madurai",
        "lat": 9.9920,
        "lng": 78.0410,
        "pincode": "625402",
        "catchment_population": 32000,
        "medical_officer_in_charge": "Dr. K. Revathi",
        "contact_phone": "+91 94430 81002",
        "tier": "Peri-Urban Primary",
        "power_backup_hours": 16,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:48:00Z"
    },
    {
        "id": "TN-MAD-003",
        "name": "CHC Vadipatti",
        "type": "CHC",
        "state_code": "TN",
        "district": "Madurai",
        "lat": 10.0712,
        "lng": 77.9620,
        "pincode": "625218",
        "catchment_population": 84000,
        "medical_officer_in_charge": "Dr. T. Kannan",
        "contact_phone": "+91 94430 81003",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "TN-MAD-004",
        "name": "Govt Rajaji Medical College & District Hub",
        "type": "DH",
        "state_code": "TN",
        "district": "Madurai",
        "lat": 9.9252,
        "lng": 78.1360,
        "pincode": "625020",
        "catchment_population": 850000,
        "medical_officer_in_charge": "Dr. A. Rathinavel",
        "contact_phone": "+91 94430 89100",
        "tier": "Apex Tertiary Teaching Hub & Depot",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },
    {
        "id": "TN-CHE-001",
        "name": "Rajiv Gandhi Govt General Hospital",
        "type": "DH",
        "state_code": "TN",
        "district": "Chennai",
        "lat": 13.0805,
        "lng": 80.2785,
        "pincode": "600003",
        "catchment_population": 1300000,
        "medical_officer_in_charge": "Dr. E. Theranirajan",
        "contact_phone": "+91 94430 89101",
        "tier": "Apex State Referral & Central Depot",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:58:00Z"
    },

    # ==================== TELANGANA ====================
    {
        "id": "TG-HYD-001",
        "name": "UPHC Golconda",
        "type": "PHC",
        "state_code": "TG",
        "district": "Hyderabad",
        "lat": 17.3833,
        "lng": 78.4011,
        "pincode": "500008",
        "catchment_population": 48000,
        "medical_officer_in_charge": "Dr. Mohammed Asif",
        "contact_phone": "+91 98490 24001",
        "tier": "Urban Primary",
        "power_backup_hours": 20,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "TG-RAN-001",
        "name": "CHC Maheshwaram",
        "type": "CHC",
        "state_code": "TG",
        "district": "Rangareddy",
        "lat": 17.1300,
        "lng": 78.4300,
        "pincode": "501359",
        "catchment_population": 89000,
        "medical_officer_in_charge": "Dr. V. Swaroopa",
        "contact_phone": "+91 98490 24002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "TG-HYD-002",
        "name": "Osmania General & District Apex Hospital",
        "type": "DH",
        "state_code": "TG",
        "district": "Hyderabad",
        "lat": 17.3750,
        "lng": 78.4770,
        "pincode": "500012",
        "catchment_population": 920000,
        "medical_officer_in_charge": "Dr. B. Nagender",
        "contact_phone": "+91 98490 24003",
        "tier": "Apex District Tertiary Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== TRIPURA ====================
    {
        "id": "TR-WT-001",
        "name": "PHC Ranirbazar",
        "type": "PHC",
        "state_code": "TR",
        "district": "West Tripura",
        "lat": 23.8400,
        "lng": 91.3600,
        "pincode": "799035",
        "catchment_population": 24000,
        "medical_officer_in_charge": "Dr. Subrata Debbarma",
        "contact_phone": "+91 94361 88001",
        "tier": "Rural Primary",
        "power_backup_hours": 18,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "TR-WT-002",
        "name": "CHC Mohanpur",
        "type": "CHC",
        "state_code": "TR",
        "district": "West Tripura",
        "lat": 23.9700,
        "lng": 91.3600,
        "pincode": "799211",
        "catchment_population": 51000,
        "medical_officer_in_charge": "Dr. Jhunu Bhattacharya",
        "contact_phone": "+91 94361 88002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "TR-WT-003",
        "name": "IGM District Referral Hospital Agartala",
        "type": "DH",
        "state_code": "TR",
        "district": "West Tripura",
        "lat": 23.8350,
        "lng": 91.2810,
        "pincode": "799001",
        "catchment_population": 320000,
        "medical_officer_in_charge": "Dr. Sharmistha Sarkar",
        "contact_phone": "+91 94361 88003",
        "tier": "Apex State Referral Center",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== UTTAR PRADESH ====================
    {
        "id": "UP-VAR-001",
        "name": "PHC Cholapur",
        "type": "PHC",
        "state_code": "UP",
        "district": "Varanasi",
        "lat": 25.4372,
        "lng": 82.9715,
        "pincode": "221101",
        "catchment_population": 34500,
        "medical_officer_in_charge": "Dr. Vivek Anand Srivastava",
        "contact_phone": "+91 94152 48101",
        "tier": "Rural Primary",
        "power_backup_hours": 14,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "UP-VAR-002",
        "name": "PHC Harhua",
        "type": "PHC",
        "state_code": "UP",
        "district": "Varanasi",
        "lat": 25.3855,
        "lng": 82.9248,
        "pincode": "221105",
        "catchment_population": 42000,
        "medical_officer_in_charge": "Dr. Priya Verma",
        "contact_phone": "+91 94152 48102",
        "tier": "Peri-Urban Primary",
        "power_backup_hours": 16,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:48:00Z"
    },
    {
        "id": "UP-VAR-003",
        "name": "CHC Pindra",
        "type": "CHC",
        "state_code": "UP",
        "district": "Varanasi",
        "lat": 25.5312,
        "lng": 82.8145,
        "pincode": "221206",
        "catchment_population": 85000,
        "medical_officer_in_charge": "Dr. H.C. Maurya",
        "contact_phone": "+91 94152 48103",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "UP-VAR-004",
        "name": "Pt. Deen Dayal Upadhyaya District Hospital",
        "type": "DH",
        "state_code": "UP",
        "district": "Varanasi",
        "lat": 25.3340,
        "lng": 82.9812,
        "pincode": "221002",
        "catchment_population": 650000,
        "medical_officer_in_charge": "Dr. R.K. Singh",
        "contact_phone": "+91 94152 48104",
        "tier": "Apex District Tertiary Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },
    {
        "id": "UP-LKO-001",
        "name": "King George's Medical University Apex Center",
        "type": "DH",
        "state_code": "UP",
        "district": "Lucknow",
        "lat": 26.8687,
        "lng": 80.9168,
        "pincode": "226003",
        "catchment_population": 1400000,
        "medical_officer_in_charge": "Prof. Soniya Nityanand",
        "contact_phone": "+91 94152 48105",
        "tier": "State Apex Teaching Hospital & Vaccine Depot",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:58:00Z"
    },
    {
        "id": "UP-GKP-001",
        "name": "BRD Medical College & Nehru Hospital",
        "type": "DH",
        "state_code": "UP",
        "district": "Gorakhpur",
        "lat": 26.7865,
        "lng": 83.3812,
        "pincode": "273013",
        "catchment_population": 890000,
        "medical_officer_in_charge": "Dr. Ganesh Kumar",
        "contact_phone": "+91 94152 48106",
        "tier": "Regional Encephalitis Hub & Tertiary Center",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:59:00Z"
    },

    # ==================== UTTARAKHAND ====================
    {
        "id": "UK-DEH-001",
        "name": "PHC Sahaspur",
        "type": "PHC",
        "state_code": "UK",
        "district": "Dehradun",
        "lat": 30.3800,
        "lng": 77.8100,
        "pincode": "248197",
        "catchment_population": 29000,
        "medical_officer_in_charge": "Dr. Pradeep Negi",
        "contact_phone": "+91 94120 27001",
        "tier": "Valley Primary",
        "power_backup_hours": 18,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "UK-DEH-002",
        "name": "CHC Doiwala",
        "type": "CHC",
        "state_code": "UK",
        "district": "Dehradun",
        "lat": 30.1800,
        "lng": 78.1200,
        "pincode": "248140",
        "catchment_population": 68000,
        "medical_officer_in_charge": "Dr. Vandana Semwal",
        "contact_phone": "+91 94120 27002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "UK-DEH-003",
        "name": "Coronation District Hospital Dehradun",
        "type": "DH",
        "state_code": "UK",
        "district": "Dehradun",
        "lat": 30.3250,
        "lng": 78.0410,
        "pincode": "248001",
        "catchment_population": 420000,
        "medical_officer_in_charge": "Dr. B.C. Ramola",
        "contact_phone": "+91 94120 27003",
        "tier": "Apex District Tertiary Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== WEST BENGAL ====================
    {
        "id": "WB-S24-001",
        "name": "PHC Basanti",
        "type": "PHC",
        "state_code": "WB",
        "district": "South 24 Parganas",
        "lat": 22.1970,
        "lng": 88.7180,
        "pincode": "743312",
        "catchment_population": 38000,
        "medical_officer_in_charge": "Dr. Arindam Mukherjee",
        "contact_phone": "+91 98300 71001",
        "tier": "Sundarbans Delta Primary",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "WB-S24-002",
        "name": "PHC Gosaba",
        "type": "PHC",
        "state_code": "WB",
        "district": "South 24 Parganas",
        "lat": 22.1650,
        "lng": 88.8070,
        "pincode": "743370",
        "catchment_population": 27000,
        "medical_officer_in_charge": "Dr. Tanmay Biswas",
        "contact_phone": "+91 98300 71002",
        "tier": "Sundarbans Island Primary",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:48:00Z"
    },
    {
        "id": "WB-S24-003",
        "name": "CHC Canning",
        "type": "CHC",
        "state_code": "WB",
        "district": "South 24 Parganas",
        "lat": 22.3110,
        "lng": 88.6590,
        "pincode": "743329",
        "catchment_population": 110000,
        "medical_officer_in_charge": "Dr. Subrata Roy",
        "contact_phone": "+91 98300 71003",
        "tier": "Sundarbans Gateway Community Hospital",
        "power_backup_hours": 36,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "WB-KOL-001",
        "name": "Calcutta National Medical College & Hospital",
        "type": "DH",
        "state_code": "WB",
        "district": "Kolkata",
        "lat": 22.5401,
        "lng": 88.3686,
        "pincode": "700014",
        "catchment_population": 920000,
        "medical_officer_in_charge": "Dr. Sandip Ghosh",
        "contact_phone": "+91 98300 71004",
        "tier": "Apex Regional Teaching Hub & Depot",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },
    {
        "id": "WB-S24-004",
        "name": "Diamond Harbour District Sub-Divisional Hospital",
        "type": "DH",
        "state_code": "WB",
        "district": "South 24 Parganas",
        "lat": 22.1882,
        "lng": 88.1925,
        "pincode": "743331",
        "catchment_population": 490000,
        "medical_officer_in_charge": "Dr. Utpal Dan",
        "contact_phone": "+91 98300 71005",
        "tier": "Coastal District Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:58:00Z"
    },

    # ==================== ANDAMAN & NICOBAR ISLANDS ====================
    {
        "id": "AN-SA-001",
        "name": "PHC Ferrargunj",
        "type": "PHC",
        "state_code": "AN",
        "district": "South Andaman",
        "lat": 11.7200,
        "lng": 92.6500,
        "pincode": "744206",
        "catchment_population": 14000,
        "medical_officer_in_charge": "Dr. R.K. Halder",
        "contact_phone": "+91 94342 81001",
        "tier": "Island Primary",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "AN-SA-002",
        "name": "CHC Bambooflat",
        "type": "CHC",
        "state_code": "AN",
        "district": "South Andaman",
        "lat": 11.7000,
        "lng": 92.7100,
        "pincode": "744107",
        "catchment_population": 31000,
        "medical_officer_in_charge": "Dr. Rekha Das",
        "contact_phone": "+91 94342 81002",
        "tier": "Island Community Hospital",
        "power_backup_hours": 36,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "AN-SA-003",
        "name": "G.B. Pant District Hospital Port Blair",
        "type": "DH",
        "state_code": "AN",
        "district": "South Andaman",
        "lat": 11.6660,
        "lng": 92.7420,
        "pincode": "744101",
        "catchment_population": 195000,
        "medical_officer_in_charge": "Dr. M.K. Saha",
        "contact_phone": "+91 94342 81003",
        "tier": "Apex Island Referral Hospital",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== CHANDIGARH ====================
    {
        "id": "CH-CHD-001",
        "name": "HWC / UPHC Sector 22",
        "type": "PHC",
        "state_code": "CH",
        "district": "Chandigarh",
        "lat": 30.7250,
        "lng": 76.7750,
        "pincode": "160022",
        "catchment_population": 32000,
        "medical_officer_in_charge": "Dr. Navneet Kaur",
        "contact_phone": "+91 98720 30001",
        "tier": "Urban Primary Health Centre",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "CH-CHD-002",
        "name": "Civil Hospital / CHC Sector 45",
        "type": "CHC",
        "state_code": "CH",
        "district": "Chandigarh",
        "lat": 30.7080,
        "lng": 76.7620,
        "pincode": "160047",
        "catchment_population": 85000,
        "medical_officer_in_charge": "Dr. Parminder Singh",
        "contact_phone": "+91 98720 30002",
        "tier": "Urban Community Health Centre",
        "power_backup_hours": 36,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "CH-CHD-003",
        "name": "Govt Multi-Specialty District Hospital Sector 16",
        "type": "DH",
        "state_code": "CH",
        "district": "Chandigarh",
        "lat": 30.7480,
        "lng": 76.7820,
        "pincode": "160015",
        "catchment_population": 420000,
        "medical_officer_in_charge": "Dr. Suman Singh",
        "contact_phone": "+91 98720 30003",
        "tier": "Apex UT Multi-Specialty Hospital",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== DADRA & NAGAR HAVELI & DAMAN & DIU ====================
    {
        "id": "DN-DNH-001",
        "name": "PHC Naroli",
        "type": "PHC",
        "state_code": "DN",
        "district": "Dadra and Nagar Haveli",
        "lat": 20.2100,
        "lng": 72.9900,
        "pincode": "396235",
        "catchment_population": 26000,
        "medical_officer_in_charge": "Dr. Alpesh Patel",
        "contact_phone": "+91 98240 31001",
        "tier": "Rural Primary",
        "power_backup_hours": 18,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "DN-DAM-001",
        "name": "CHC Moti Daman",
        "type": "CHC",
        "state_code": "DN",
        "district": "Daman",
        "lat": 20.4100,
        "lng": 72.8400,
        "pincode": "396220",
        "catchment_population": 62000,
        "medical_officer_in_charge": "Dr. Shailesh Arlekar",
        "contact_phone": "+91 98240 31002",
        "tier": "Coastal Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "DN-DNH-002",
        "name": "Shri Vinoba Bhave Civil District Hospital Silvassa",
        "type": "DH",
        "state_code": "DN",
        "district": "Dadra and Nagar Haveli",
        "lat": 20.2730,
        "lng": 73.0080,
        "pincode": "396230",
        "catchment_population": 310000,
        "medical_officer_in_charge": "Dr. V.K. Das",
        "contact_phone": "+91 98240 31003",
        "tier": "Apex UT District Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== DELHI ====================
    {
        "id": "DL-CEN-001",
        "name": "UPHC Chandni Chowk",
        "type": "PHC",
        "state_code": "DL",
        "district": "Central Delhi",
        "lat": 28.6560,
        "lng": 77.2300,
        "pincode": "110006",
        "catchment_population": 52000,
        "medical_officer_in_charge": "Dr. Sunita Aggarwal",
        "contact_phone": "+91 98100 32001",
        "tier": "High-Density Urban Primary",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "DL-SOU-001",
        "name": "CHC Mehrauli",
        "type": "CHC",
        "state_code": "DL",
        "district": "South Delhi",
        "lat": 28.5180,
        "lng": 77.1850,
        "pincode": "110030",
        "catchment_population": 130000,
        "medical_officer_in_charge": "Dr. Pankaj Arora",
        "contact_phone": "+91 98100 32002",
        "tier": "Urban Community Health Centre",
        "power_backup_hours": 36,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "DL-ND-001",
        "name": "Dr. Ram Manohar Lohia Hospital & Central Depot",
        "type": "DH",
        "state_code": "DL",
        "district": "New Delhi",
        "lat": 28.6250,
        "lng": 77.2000,
        "pincode": "110001",
        "catchment_population": 980000,
        "medical_officer_in_charge": "Dr. Ajay Shukla",
        "contact_phone": "+91 98100 32003",
        "tier": "National Apex Central Hospital",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },
    {
        "id": "DL-SW-001",
        "name": "UPHC Najafgarh Rural Training Unit",
        "type": "PHC",
        "state_code": "DL",
        "district": "South West Delhi",
        "lat": 28.6090,
        "lng": 76.9850,
        "pincode": "110043",
        "catchment_population": 61000,
        "medical_officer_in_charge": "Dr. Manoj Sharma",
        "contact_phone": "+91 98100 32004",
        "tier": "Peri-Urban Primary",
        "power_backup_hours": 20,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:58:00Z"
    },

    # ==================== JAMMU & KASHMIR ====================
    {
        "id": "JK-SRI-001",
        "name": "PHC Hazratbal",
        "type": "PHC",
        "state_code": "JK",
        "district": "Srinagar",
        "lat": 34.1250,
        "lng": 74.8400,
        "pincode": "190006",
        "catchment_population": 31000,
        "medical_officer_in_charge": "Dr. Tariq Ahmad",
        "contact_phone": "+91 94190 33001",
        "tier": "Valley Primary",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "JK-GAN-001",
        "name": "CHC Ganderbal",
        "type": "CHC",
        "state_code": "JK",
        "district": "Ganderbal",
        "lat": 34.2150,
        "lng": 74.7800,
        "pincode": "191201",
        "catchment_population": 74000,
        "medical_officer_in_charge": "Dr. Farooq Jan",
        "contact_phone": "+91 94190 33002",
        "tier": "Sub-District Community Hospital",
        "power_backup_hours": 36,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "JK-SRI-002",
        "name": "SMHS Hospital & District Medical Center Srinagar",
        "type": "DH",
        "state_code": "JK",
        "district": "Srinagar",
        "lat": 34.0900,
        "lng": 74.8050,
        "pincode": "190010",
        "catchment_population": 580000,
        "medical_officer_in_charge": "Dr. Nazir Choudhary",
        "contact_phone": "+91 94190 33003",
        "tier": "Apex Regional Teaching Hub & Depot",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },
    {
        "id": "JK-JAM-001",
        "name": "CHC Akhnoor",
        "type": "CHC",
        "state_code": "JK",
        "district": "Jammu",
        "lat": 32.8900,
        "lng": 74.7400,
        "pincode": "181201",
        "catchment_population": 68000,
        "medical_officer_in_charge": "Dr. Rajeshwar Sharma",
        "contact_phone": "+91 94190 33004",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:58:00Z"
    },

    # ==================== LADAKH ====================
    {
        "id": "LA-LEH-001",
        "name": "PHC Chushot",
        "type": "PHC",
        "state_code": "LA",
        "district": "Leh",
        "lat": 34.0800,
        "lng": 77.6200,
        "pincode": "194101",
        "catchment_population": 11000,
        "medical_officer_in_charge": "Dr. Stanzin Norboo",
        "contact_phone": "+91 94191 34001",
        "tier": "High Altitude Primary (3500m)",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "LA-LEH-002",
        "name": "CHC Khaltsi",
        "type": "CHC",
        "state_code": "LA",
        "district": "Leh",
        "lat": 34.3200,
        "lng": 76.8800,
        "pincode": "194106",
        "catchment_population": 22000,
        "medical_officer_in_charge": "Dr. Tsering Wangchuk",
        "contact_phone": "+91 94191 34002",
        "tier": "High Altitude Community Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "LA-LEH-003",
        "name": "SNM (Sonam Norboo Memorial) District Hospital Leh",
        "type": "DH",
        "state_code": "LA",
        "district": "Leh",
        "lat": 34.1640,
        "lng": 77.5840,
        "pincode": "194101",
        "catchment_population": 140000,
        "medical_officer_in_charge": "Dr. Padma Dolkar",
        "contact_phone": "+91 94191 34003",
        "tier": "Apex High-Altitude UT Hospital",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== LAKSHADWEEP ====================
    {
        "id": "LD-KAV-001",
        "name": "PHC Agatti Island",
        "type": "PHC",
        "state_code": "LD",
        "district": "Lakshadweep",
        "lat": 10.8530,
        "lng": 72.1920,
        "pincode": "682553",
        "catchment_population": 8500,
        "medical_officer_in_charge": "Dr. K.P. Mohammed",
        "contact_phone": "+91 94471 35001",
        "tier": "Isolated Coral Atoll Primary",
        "power_backup_hours": 36,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "LD-KAV-002",
        "name": "CHC Andrott Island",
        "type": "CHC",
        "state_code": "LD",
        "district": "Lakshadweep",
        "lat": 10.8250,
        "lng": 73.6800,
        "pincode": "682551",
        "catchment_population": 16000,
        "medical_officer_in_charge": "Dr. P.I. Faisal",
        "contact_phone": "+91 94471 35002",
        "tier": "Island Community Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "LD-KAV-003",
        "name": "Indira Gandhi District Hospital Kavaratti",
        "type": "DH",
        "state_code": "LD",
        "district": "Lakshadweep",
        "lat": 10.5650,
        "lng": 72.6400,
        "pincode": "682555",
        "catchment_population": 42000,
        "medical_officer_in_charge": "Dr. Abdul Shukoor",
        "contact_phone": "+91 94471 35003",
        "tier": "Apex Island UT Hospital",
        "power_backup_hours": 72,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    },

    # ==================== PUDUCHERRY ====================
    {
        "id": "PY-PUD-001",
        "name": "PHC Villianur",
        "type": "PHC",
        "state_code": "PY",
        "district": "Puducherry",
        "lat": 11.9160,
        "lng": 79.7600,
        "pincode": "605110",
        "catchment_population": 31000,
        "medical_officer_in_charge": "Dr. G. Senthil Kumar",
        "contact_phone": "+91 94432 36001",
        "tier": "Rural Primary",
        "power_backup_hours": 18,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:45:00Z"
    },
    {
        "id": "PY-PUD-002",
        "name": "CHC Karikalampakkam",
        "type": "CHC",
        "state_code": "PY",
        "district": "Puducherry",
        "lat": 11.8700,
        "lng": 79.7300,
        "pincode": "605007",
        "catchment_population": 64000,
        "medical_officer_in_charge": "Dr. R. Malarvizhi",
        "contact_phone": "+91 94432 36002",
        "tier": "Secondary Referral Community Hospital",
        "power_backup_hours": 24,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:50:00Z"
    },
    {
        "id": "PY-PUD-003",
        "name": "Indira Gandhi Govt General Hospital & Postgraduate Institute",
        "type": "DH",
        "state_code": "PY",
        "district": "Puducherry",
        "lat": 11.9350,
        "lng": 79.8270,
        "pincode": "605001",
        "catchment_population": 410000,
        "medical_officer_in_charge": "Dr. S. Sevvel",
        "contact_phone": "+91 94432 36003",
        "tier": "Apex UT Tertiary Teaching Hospital",
        "power_backup_hours": 48,
        "cold_chain_solar": True,
        "last_sync_timestamp": "2026-09-27T10:55:00Z"
    }
]

# Baseline resource configurations based on facility type
RESOURCE_TIER_SPECS = {
    "PHC": {
        "beds": {
            "general_male": 3,
            "general_female": 3,
            "oxygen_supported": 2,
            "icu_ventilator": 0,
            "maternity_delivery": 2
        },
        "staff": {
            "medical_officers": {"sanctioned": 2, "avg_present": 2},
            "staff_nurses": {"sanctioned": 3, "avg_present": 3},
            "anm_workers": {"sanctioned": 5, "avg_present": 4},
            "asha_coordinators": {"sanctioned": 12, "avg_present": 11},
            "pharmacists": {"sanctioned": 1, "avg_present": 1},
            "lab_technicians": {"sanctioned": 1, "avg_present": 1}
        },
        "daily_footfall_range": [70, 160],
        "stock_multiplier": 1.0
    },
    "CHC": {
        "beds": {
            "general_male": 12,
            "general_female": 12,
            "oxygen_supported": 10,
            "icu_ventilator": 2,
            "maternity_delivery": 6
        },
        "staff": {
            "medical_officers": {"sanctioned": 6, "avg_present": 5},
            "staff_nurses": {"sanctioned": 12, "avg_present": 11},
            "anm_workers": {"sanctioned": 10, "avg_present": 9},
            "asha_coordinators": {"sanctioned": 25, "avg_present": 23},
            "pharmacists": {"sanctioned": 3, "avg_present": 3},
            "lab_technicians": {"sanctioned": 3, "avg_present": 2}
        },
        "daily_footfall_range": [220, 480],
        "stock_multiplier": 3.8
    },
    "DH": {
        "beds": {
            "general_male": 80,
            "general_female": 80,
            "oxygen_supported": 60,
            "icu_ventilator": 20,
            "maternity_delivery": 30
        },
        "staff": {
            "medical_officers": {"sanctioned": 28, "avg_present": 25},
            "staff_nurses": {"sanctioned": 65, "avg_present": 60},
            "anm_workers": {"sanctioned": 20, "avg_present": 19},
            "asha_coordinators": {"sanctioned": 50, "avg_present": 48},
            "pharmacists": {"sanctioned": 8, "avg_present": 8},
            "lab_technicians": {"sanctioned": 10, "avg_present": 9}
        },
        "daily_footfall_range": [900, 1800],
        "stock_multiplier": 15.0
    }
}
